### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by RockMan1966** [emailwzg/U-Segformer-Hyper#1]
您好，请问在section阶段，您是如何进行的数据预处理的呢，输入的尺寸是多大呢

**Comment by emailwzg** [comment]
预处理过程见section_train.py。输入尺寸是原始地震剖面大小。

**Comment by RockMan1966** [comment]
![image](https://github.com/emailwzg/U-Segformer-Hyper/assets/57976543/f63f4a3e-59ab-44ff-b9f2-a6d7b6ea5d17)
你好，我使用两张3090,得到的效果和论文略有差距，我使用的bs为8，请问我还有哪里没有设置正确嘛
